spring:
  application:
    name: spends
  threads:
    virtual:
      enabled: true
  aot:
    enabled: true
server:
  port: 8000
management:
  server:
    port: 8001
  endpoints:
    enabled-by-default: true
    web:
      base-path: /manage
      exposure:
        include: "*"
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs/swagger-ui
    supportedSubmitMethods: get,post,delete,head,patch,put,options
scalar:
  enabled: true
settings:
  defaultLanguageCode: en
spends:
  queries:
    language: language
  headers:
    count: spends_count
    errors:
      messages: errors_messages
      codes: errors_codes